# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerAT05 < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://https://gerhard-dagger.s3-eu-west-1.amazonaws.com/dagger/releases/0.5.1/dagger_v0.5.1_darwin_arm64.tar.gz"
      sha256 "26c3bdd8ecd1731d8dc72da3e25b30ce25ec5e6b5e29b72a19fb0e65fee37d62"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://https://gerhard-dagger.s3-eu-west-1.amazonaws.com/dagger/releases/0.5.1/dagger_v0.5.1_darwin_amd64.tar.gz"
      sha256 "72945be97400ceabacf0b50851a2d9bde2a1100ecadd3329f1cd0b64dac1350d"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://https://gerhard-dagger.s3-eu-west-1.amazonaws.com/dagger/releases/0.5.1/dagger_v0.5.1_linux_arm64.tar.gz"
      sha256 "069d476c11b124d3aa19d3290e3817af132ddf5415184d86d663b46ceaaacf50"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://https://gerhard-dagger.s3-eu-west-1.amazonaws.com/dagger/releases/0.5.1/dagger_v0.5.1_linux_amd64.tar.gz"
      sha256 "0903d440248d38778259bb53b47f8fcb83af1af9215611a6c59ec7dd77b54484"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
