# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerCue < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.0/dagger-cue_0.1.0_darwin_amd64.tar.gz"
      sha256 "4ec9421feca1dde16cf07486b41a6f23516e1f3bee4a7cf94f13a289fe94721b"

      def install
        bin.install "dagger-cue"
      end
    end
    if Hardware::CPU.arm?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.0/dagger-cue_0.1.0_darwin_arm64.tar.gz"
      sha256 "626b5a34ecf5c102a6abe71d3a61a7f33d04b69c8662988f5742d984d326e679"

      def install
        bin.install "dagger-cue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.0/dagger-cue_0.1.0_linux_arm64.tar.gz"
      sha256 "391a36cb40dbe0b7dde7dc024b790d2e3d5f4ca8d3cae505ae20eea3e3109c94"

      def install
        bin.install "dagger-cue"
      end
    end
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.0/dagger-cue_0.1.0_linux_amd64.tar.gz"
      sha256 "7ed499ed9a1468748bfb9b71ca78790ff2e2390eaf1f4b0be863eaa64c3c96c8"

      def install
        bin.install "dagger-cue"
      end
    end
  end

  test do
    system "#{bin}/dagger-cue version"
  end
end
