# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagger < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.6.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_darwin_amd64.tar.gz"
      sha256 "b20462f7e94669ddd007d5b8e0659fbdc46132da30d176ea2a2d78bbf62f789e"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.arm?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_darwin_arm64.tar.gz"
      sha256 "dff19aebb62c6a87e8f469779083129f11f491a24fe3ccf309fb31ec7011cf3b"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_linux_arm64.tar.gz"
      sha256 "581a08c675a0d70df681a60f8ea3f7f7db56e21b81aa1c371485389aca5c0dc9"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_linux_amd64.tar.gz"
      sha256 "8f2567bbd1b6ed48b0b1a41346a0dcf67aabf06e33e257772e3f5a19e20d5511"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
