# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerCue < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.1/dagger-cue_v0.1.1_darwin_amd64.tar.gz"
      sha256 "ce1e8d51ae1e49d58196adcf865c940099beb5062215a6d3ab3cc15add8ed6b8"

      def install
        bin.install "dagger-cue"
      end
    end
    if Hardware::CPU.arm?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.1/dagger-cue_v0.1.1_darwin_arm64.tar.gz"
      sha256 "7dfb964f65eba497192d9ea9cfd468123a6b7b52e7e5beb86eae742bf58254a8"

      def install
        bin.install "dagger-cue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.1/dagger-cue_v0.1.1_linux_arm64.tar.gz"
      sha256 "da240ff201305dbcef0a0f081195986eb17b4fc7a6d5401f58e91712f4ac3aed"

      def install
        bin.install "dagger-cue"
      end
    end
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger-cue/releases/0.1.1/dagger-cue_v0.1.1_linux_amd64.tar.gz"
      sha256 "43625535da3d5b696f774b55ebc9efd8dfa3558e61a12e049e06157b70c03c5c"

      def install
        bin.install "dagger-cue"
      end
    end
  end

  test do
    system "#{bin}/dagger-cue version"
  end
end
