# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerAT06 < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.1/dagger_v0.6.1_darwin_amd64.tar.gz"
      sha256 "605d72b746e9d4ce9b0aab0fb1dafb7790eed30c4c18313282bcce5dc16ff549"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.arm?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.1/dagger_v0.6.1_darwin_arm64.tar.gz"
      sha256 "d5ad121deb0b86727c15d4e5f20a2472d435e64d5a7d61da1d7c485d705ce3cf"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.1/dagger_v0.6.1_linux_arm64.tar.gz"
      sha256 "3bfdf2c2c87de5967f654e3822be7714d2fcb3d5af62bfcd2798982f8f58fe49"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.1/dagger_v0.6.1_linux_amd64.tar.gz"
      sha256 "af8fa3bb500f38dbeb4f410470610040a614a5388872f0d1d2af72aeb07260f3"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
