# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagger < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.6.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_darwin_amd64.tar.gz"
      sha256 "ad3db4dcc205a7cac9ad646baf4ae136d38897436c07cec5fc9aa567bd471bff"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.arm?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_darwin_arm64.tar.gz"
      sha256 "109fe2a59c6b4fd604e6d806f0db84910ffdb265fc56c212518e5d4d2f72ea54"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_linux_arm64.tar.gz"
      sha256 "b58d3948f42c1870b30d8fe64667bdda2b14687a8f9fc6f75addb8263ae799d0"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.6.4/dagger_v0.6.4_linux_amd64.tar.gz"
      sha256 "679a2aafb5782897c6597af5442ab06b44eb178accdf29c2928511c1afcd19b6"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
