# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DaggerAT03 < Formula
  desc "Dagger is a programmable deployment system."
  homepage "https://github.com/dagger/dagger"
  version "0.3.0-alpha.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_darwin_amd64.tar.gz"
      sha256 "052bdd4ca821d21a29c8c707ffc0a04e0ccfc34001a85f823ac850d6d8ad72b6"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.arm?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_darwin_arm64.tar.gz"
      sha256 "b8ea8991714b07ce0d94e92728ef4d6d9e595ef2695b3317c93f9f346de636ee"

      def install
        bin.install "dagger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_linux_arm64.tar.gz"
      sha256 "cef68471db2d6df01996efa19d90332cf8b27b9c356d290288ec05b37a2e735f"

      def install
        bin.install "dagger"
      end
    end
    if Hardware::CPU.intel?
      url "https://gerhard-dagger.s3.eu-west-1.amazonaws.com/dagger/releases/0.3.0-alpha.1/dagger_v0.3.0-alpha.1_linux_amd64.tar.gz"
      sha256 "a0bab7ab54097400e9628c2d8c528c135df6590731b52265b57e43a92fa63468"

      def install
        bin.install "dagger"
      end
    end
  end

  test do
    system "#{bin}/dagger version"
  end
end
